spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
      minimum-idle: 3
      pool-name: LibraryH2Pool
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: false # Por segurança, deixe como false em produção
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        # Configurações adicionais de performance
        generate_statistics: true
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        # Para mostrar parâmetros de queries
        use_sql_comments: true
  sql:
    init:
      mode: always # Para executar scripts data.sql/schema.sql
      platform: h2 # Especifica o banco para scripts SQL