spring:
  application:
    name: Arquitetura Spring
  jpa:
    show-sql: true
  main:
    lazy-initialization: false

app:

  motandora:
    motor-padrao: 130
  config:
    variavel: valor da variavel X
    valor1: 500